### PR TITLE
camera parameters & tap2wake controller 

### PR DESCRIPTION
**Pull request by ganeshi4u**

### CODE REVIEW

**Comment by mohancm** [comment]
I have added camera parameters already!
I didn't pushed it , yet!
Anyway, thanks

**Comment by ganeshi4u** [comment]
Good! 
was just testing your LineageOS14.1 to fix any bugs. I think you have managed to fix everything so far. Have you fixed the wifi issue? i see that a lib named **"libhw.so"** is missing from the logs.
Let me know if you need any help.

**Comment by mohancm** [comment]
Almost going well, WiFi issue still persist, and Bluetooth is now intermittent!
I am experimenting with many changes! Once if i gets any improvements I will push them!
And for hwm.so, 
Log says that file is missing, but I have provided it already! Still digging into it.

**Comment by pinnamanivenkat** [comment]
If in such case, go to libEGL and then loader.cpp and then add there line to call up the library, If you really want the library to get called :) 
Good luck :D

**Comment by mohancm** [comment]
Not necessary, I have a patch for that. The case here that lib is not causing any major issue
Though I have recovered in my latest build!

**Pull request closed without merging**
