### PR TITLE
Xen0n`s trick [2/2]

### PR DESCRIPTION
**Pull request by DidntRead**

### CODE REVIEW

**Comment by mohancm** [comment]
Can you provide me description for this?

**Comment by DidntRead** [comment]
It converts _ZN7android5Fence4waitEj to _ZN7android5Fence4waitEi and removes the need for the shim 

_Sent from my LENOVO Lenovo A7010a48 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by mohancm** [comment]
Did you tested this?

**Comment by DidntRead** [comment]
I haven't on the A7010 but I have on my other phone

**Comment by mohancm** [comment]
Alright, I need to test it first
Later I will merge it
Thank you

**Pull request merged**
