### PR TITLE
Might bring that blue led colour on notification

### PR DESCRIPTION
**Pull request by dg28gadhavi**
I don't know it will work or not but should give a shot

### CODE REVIEW

**Comment by Zormax** [comment]
Revert this commit and Use: mAutoGenerateNotificationColor = false;
in file: frameworks/base/services/core/java/com/android/server/notification/NotificationManagerService.java

**Comment by mohancm** [comment]
@Zormax thanks for the tip,
Will try that :)

**Comment by dg28gadhavi** [comment]
@Zormax i tried as you said reverted that commit  and disabled auto notification colour generation now the led's are  working perfectly fine in my Los but can You help me how to resolve the HW decoder issue (the YouTube video lag) and video recording if you help us it will be highly appreciable ☺☺☺

**Comment by Zormax** [comment]
Всё не так просто... я использую новое ядро и новые библиотеки. Возможно, я выложу полное дерево через неделю-две.

**Comment by dg28gadhavi** [comment]
@Zormax i have to use G-translate for it (Russian) but thanks will wait for your sources to be released ☺☺☺

**Pull request merged**
